/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs.register;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.application.Application;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.ui.ApplicationFrame;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author luis
 */
public class jframe extends javax.swing.JFrame {

    

    /**
     * Creates new form jframe
     */
    public jframe() {
        dao = new abrirefeichar();
        rankl = new ArrayList<>();
        rankl.add("sem rank");
        rankl.add("prata 1");
        rankl.add("prata 2");
        rankl.add("prata 3");
        rankl.add("prata 4");
        rankl.add("prata elite");
        rankl.add("prata elite mestre");
        rankl.add("gold nova 1");
        rankl.add("gold nova 2 ");
        rankl.add("gold nova 3");
        rankl.add("gold nova master");
        rankl.add("master guardian");
        rankl.add("master guardian 2");
        rankl.add("master guardian elite");
        rankl.add("distinguished master guardian");
        rankl.add("legendary eagle");
        rankl.add("legendary eagle master");
        rankl.add("supreme master first class");
        rankl.add("global elite");
        
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KillButton = new javax.swing.JToggleButton();
        Kda = new javax.swing.JToggleButton();
        wld = new javax.swing.JToggleButton();
        socore = new javax.swing.JButton();
        campo_kill = new javax.swing.JTextField();
        campo_assisti = new javax.swing.JTextField();
        campo_death = new javax.swing.JTextField();
        incluir = new javax.swing.JButton();
        deletar = new javax.swing.JButton();
        rank = new javax.swing.JButton();
        campo_score = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        patente = new java.awt.Choice();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        win = new javax.swing.JCheckBox();
        loss = new javax.swing.JCheckBox();
        draw = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        KillButton.setText("Kill");
        KillButton.setToolTipText("");
        KillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KillButtonMouseClicked(evt);
            }
        });

        Kda.setText("KDA");
        Kda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KdaMouseClicked(evt);
            }
        });

        wld.setText("WLD");
        wld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wldMouseClicked(evt);
            }
        });

        socore.setText("Score");
        socore.setActionCommand("score");
        socore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                socoreMouseClicked(evt);
            }
        });
        socore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socoreActionPerformed(evt);
            }
        });

        incluir.setText("Incluir");
        incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirActionPerformed(evt);
            }
        });

        deletar.setText("Deletar");
        deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarActionPerformed(evt);
            }
        });

        rank.setText("Rank");

        campo_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_scoreActionPerformed(evt);
            }
        });

        jLabel1.setText("Kill :");

        jLabel2.setText("Assists :");

        jLabel3.setText("Death :");

        jLabel4.setText("Score :");

        jLabel5.setText("Patente :");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kill", "Assist", "Death","WLD" ,"score","rank"
            }
        ));
        jScrollPane2.setViewportView(tabela);

        win.setText("WIN");
        win.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winActionPerformed(evt);
            }
        });

        loss.setText("LOSS");
        loss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lossActionPerformed(evt);
            }
        });

        draw.setText("DRAW");
        draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(KillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(Kda, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(wld, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campo_kill, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campo_assisti, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(4, 4, 4)
                                            .addComponent(campo_death, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(6, 6, 6)
                                            .addComponent(campo_score, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loss)
                                    .addComponent(win)
                                    .addComponent(draw))))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)
                                .addComponent(patente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(socore, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(rank)
                                .addGap(43, 43, 43)
                                .addComponent(deletar))
                            .addComponent(incluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KillButton)
                    .addComponent(Kda)
                    .addComponent(wld)
                    .addComponent(socore)
                    .addComponent(rank)
                    .addComponent(deletar))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_kill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(win))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loss)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel5))
                            .addComponent(patente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(draw))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campo_assisti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campo_death, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(campo_score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(incluir)))))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        dao.lerd();
        attlist();
        for(String c : rankl)
            patente.add(c);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        dao.salvaresair(0);

    }//GEN-LAST:event_formWindowClosed

    private void KillButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KillButtonMouseClicked
        // TODO add your handling code here:
        if(dao.getList1().isEmpty()){
             JOptionPane.showMessageDialog(null," sem dados");
             return;
        }
        
        geraGrafico gk = new geraGrafico("Kill", 0, dao.getList1());
        gk.pack();
        RefineryUtilities.centerFrameOnScreen(gk);
        gk.setVisible(true);
        gk.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        
        
    }//GEN-LAST:event_KillButtonMouseClicked

    private void KdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KdaMouseClicked
       
        if(dao.getList1().isEmpty()){
             JOptionPane.showMessageDialog(null," sem dados");
             return;
        }
        
        
        geraGrafico gk = new geraGrafico("KDA", 1, dao.getList1());
        gk.pack();
        RefineryUtilities.centerFrameOnScreen(gk);
        gk.setVisible(true);
        gk.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_KdaMouseClicked

    private void wldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wldMouseClicked
        // TODO add your handling code here:
        if(dao.getList1().isEmpty()){
             JOptionPane.showMessageDialog(null," sem dados");
             return;
        }
        
        geraGrafico gk = new geraGrafico("WLD", 2, dao.getList1());
        gk.pack();
        RefineryUtilities.centerFrameOnScreen(gk);
        gk.setVisible(true);
        gk.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        

    }//GEN-LAST:event_wldMouseClicked

    private void socoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socoreMouseClicked
        // TODO add your handling code here:
        if(dao.getList1().isEmpty()){
             JOptionPane.showMessageDialog(null," sem dados");
             return;
        }
        
        geraGrafico gk = new geraGrafico("Score",3, dao.getList1());
        gk.pack();
        RefineryUtilities.centerFrameOnScreen(gk);
        gk.setVisible(true);
        gk.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_socoreMouseClicked

    private void campo_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_scoreActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
        attlist();
    }//GEN-LAST:event_formComponentHidden

    private void incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirActionPerformed
        // TODO add your handling code here:
        partida p = new partida();
          if( campo_kill.getText() == null || "".equals(campo_kill.getText()) )
        {
            JOptionPane.showMessageDialog(null," kill sem nada ");
            return;
        }
        p.setKill(Integer.parseInt(campo_kill.getText()));
          if( campo_assisti.getText() == null || "".equals(campo_assisti.getText()) )
        {
            JOptionPane.showMessageDialog(null," assist sem nada ");
            return;
        }
        p.setAssist(Integer.parseInt(campo_assisti.getText()));
          if( campo_death.getText() == null || "".equals(campo_death.getText()) )
        {
            JOptionPane.showMessageDialog(null," death sem nada ");
            return;
        }
        
        p.setDeath(Integer.parseInt(campo_death.getText()));
        
        if( campo_score.getText() == null || "".equals(campo_score.getText()) || Integer.parseInt(campo_score.getText()) < (p.getKill() * 2)+p.getAssist()  )
        {
            JOptionPane.showMessageDialog(null," socore invalido ");
            return;
        }
        p.setScore(Integer.parseInt(campo_score.getText()));
        
        if(win.isSelected()){
         p.setWld(1);
        }else if (loss.isSelected()){
         p.setWld(-1);
        }else if (draw.isSelected())
        {
         p.setWld(0);
        }else{
            JOptionPane.showMessageDialog(null," campo de resultado nao selecionado ");
        }
        p.setRank(patente.getSelectedIndex());
        
        dao.addlist(p);
        
        attlist();
    }//GEN-LAST:event_incluirActionPerformed

    private void winActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winActionPerformed
        // TODO add your handling code here:
           if(win.isSelected()){
            draw.setSelected(false);
            loss.setSelected(false);
        }
    }//GEN-LAST:event_winActionPerformed

    private void drawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawActionPerformed
        // TODO add your handling code here:
        if(draw.isSelected()){
            win.setSelected(false);
            loss.setSelected(false);
        }

    }//GEN-LAST:event_drawActionPerformed

    private void lossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lossActionPerformed
        if(loss.isSelected()){
            win.setSelected(false);
            draw.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lossActionPerformed

    private void deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        if(dao.getList1().isEmpty()){
             JOptionPane.showMessageDialog(null,"sem dados");
             return;
        }
        
        List<partida> listaux = new ArrayList<>();
        try {
            listaux = dao.getList1();
        } catch (Exception ex) {
            Logger.getLogger(jframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        partida psel = listaux.get(tabela.getSelectedRow());

        try {
            dao.excluir(psel);
        } catch (Exception ex) {
            System.out.println(psel);
        }
       ((DefaultTableModel)tabela.getModel()).removeRow(tabela.getSelectedRow());

    }//GEN-LAST:event_deletarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        dao.salvaresair(0);
    }//GEN-LAST:event_formWindowClosing

    private void socoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_socoreActionPerformed

    private void attlist() {
        
        List<partida> p = dao.getList1();
       
        DefaultTableModel tp = (DefaultTableModel) tabela.getModel();
        if(tp.getRowCount() >  0){
            while(tp.getRowCount() > 0 ){
                tp.removeRow(0);
            }
        }
       
        for (partida c : p) {
            DefaultTableModel val = (DefaultTableModel) tabela.getModel();
            val.addRow(new String[]{Integer.toString(c.getKill()), Integer.toString(c.getAssist()), Integer.toString(c.getDeath()),controlawld( c.getWld() ), Integer.toString(c.getScore()),rankl.get(c.getRank()) });
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jframe().setVisible(true);
                
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Kda;
    private javax.swing.JToggleButton KillButton;
    private javax.swing.JTextField campo_assisti;
    private javax.swing.JTextField campo_death;
    private javax.swing.JTextField campo_kill;
    private javax.swing.JTextField campo_score;
    private javax.swing.JButton deletar;
    private javax.swing.JCheckBox draw;
    private javax.swing.JButton incluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox loss;
    private java.awt.Choice patente;
    private javax.swing.JButton rank;
    private javax.swing.JButton socore;
    private javax.swing.JTable tabela;
    private javax.swing.JCheckBox win;
    private javax.swing.JToggleButton wld;
    // End of variables declaration//GEN-END:variables

    private abrirefeichar dao;
    private List<String> rankl ;
   
    private String controlawld(Integer wld) {
        if (wld == 1){
        return "win";
        }else if(wld == -1 ){
        return "loss";
        }else if (wld == 0 ){
        return "draw";
        }else 
            return "erro";
    }

}
